config/routes.rb
Rails.application.routes.draw do
  resources :path_markers
  resources :locations
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord  
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  belongs_to :path_marker
  # add a before? after? creation function that will list the correct venue of the location; cannot do this based off of
  # https://stackoverflow.com/questions/55010460/find-near-banks-schools-from-latitude-and-longitude-using-geocoder-gem


  # before final save, need a callback method that will call the Google Places API and define the name of the location if 
  # it has a proper name

  # function that will take in the Google Places information (along with a relevant picture) and populate a new location to be 
  # listed using turbo stream

  # make a function that will determine if a location is in the current viewpoint for the map

  # need to define a search method that will handle the populated locations that are stored 
  def self.search(q)
    matching_designation = Location.find_by(designation: q)
    if matching_designation
      self.where(location_id: matching_designation)
    else
      Location.all
    end
  end
end

app/models/path_marker.rb
class PathMarker < ApplicationRecord
  has_many :locations
  accepts_nested_attributes_for :locations
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, :email, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    @path_markers = PathMarker.all
    @locations = Location.all

    respond_to do |format|
      format.html
      format.json # <!-- make sure you have format.json, in addition to html 
    end
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)
    
    # as part of creation need to call method inside of model that is going to populate the rest of the information needed for a location
    respond_to do |format|
      if @location.save
        format.html { redirect_to location_url(@location), notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy!

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:path_marker_id, :latitude, :longitude, :address, :designation, :name, :search)
    end
end

app/controllers/path_markers_controller.rb
class PathMarkersController < ApplicationController
  before_action :set_path_marker, only: %i[ show edit update destroy ]

  # GET /path_markers or /path_markers.json
  def index
    @path_markers = PathMarker.all
  end

  # GET /path_markers/1 or /path_markers/1.json
  def show
  end

  # GET /path_markers/new
  def new
    @path_marker = PathMarker.new
  end

  # GET /path_markers/1/edit
  def edit
  end

  # POST /path_markers or /path_markers.json
  def create
    @path_marker = PathMarker.new(path_marker_params)

    respond_to do |format|
      if @path_marker.save
        format.turbo_stream { render turbo_stream: turbo_stream.append('path_markers_list', partial: 'path_markers/path_marker', locals: { path_marker: @new_path_marker }) }
        format.json { render :show, status: :created, location: @path_marker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @path_marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /path_markers/1 or /path_markers/1.json
  def update
    respond_to do |format|
      if @path_marker.update(path_marker_params)
        format.html { redirect_to path_marker_url(@path_marker), notice: "Path marker was successfully updated." }
        format.json { render :show, status: :ok, location: @path_marker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @path_marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /path_markers/1 or /path_markers/1.json
  def destroy
    @path_marker.destroy!

    respond_to do |format|
      format.html { redirect_to path_markers_url, notice: "Path marker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_path_marker
      @path_marker = PathMarker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def path_marker_params
      params.require(:path_marker).permit(:name)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/path_markers_helper.rb
module PathMarkersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
     integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
     crossorigin=""/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.js"></script>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= action_cable_meta_tag %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
    <script>
      const RAPID_API_KEY = '<%= ENV['RAPID_API_KEY'] %>';
      const RAPID_API_URL = '<%= ENV['RAPID_API_URL'] %>';
    </script>
  </head>

  <body class="container p-2 bg-white dark:bg-gray-800 h-screen w-screen">
    <%# <nav class="bg-white border-gray-200 dark:bg-gray-800">
      <div class="flex flex-wrap items-center justify-between max-w-screen-xl mx-auto p-4">
          <a href="https://flowbite.com" class="flex items-center space-x-3 rtl:space-x-reverse">
              <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
              <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
          </a>
          <div class="flex items-center md:order-2 space-x-1 md:space-x-2 rtl:space-x-reverse">
              <a href="#" class="text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2 md:px-5 md:py-2.5 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">Login</a>
              <a href="#" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 md:px-5 md:py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Sign up</a>
              <button data-collapse-toggle="mega-menu-icons" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mega-menu-icons" aria-expanded="false">
                  <span class="sr-only">Open main menu</span>
                  <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                  </svg>
              </button>
          </div>
          <div id="mega-menu-icons" class="hidden w-full md:flex md:w-auto">
              <ul class="flex flex-col font-medium mt-4 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-transparent dark:bg-gray-800 md:dark:bg-transparent dark:border-gray-700">
                  <li>
                      <a href="#" class="block py-2 px-3 text-blue-600 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-blue-500 md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700" aria-current="page">Home</a>
                  </li>
                  <li>
                      <a href="#" class="block py-2 px-3 text-gray-900 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700">Team</a>
                  </li>
              </ul>
          </div>
      </div>
    </nav> %>
    <nav class="bg-white border-gray-200 dark:bg-gray-800">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
        </a>
        <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
          <path d="M16 0H4a2 2 0 0 0-2 2v1H1a1 1 0 0 0 0 2h1v2H1a1 1 0 0 0 0 2h1v2H1a1 1 0 0 0 0 2h1v2H1a1 1 0 0 0 0 2h1v1a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2Zm-5.5 4.5a3 3 0 1 1 0 6 3 3 0 0 1 0-6ZM13.929 17H7.071a.5.5 0 0 1-.5-.5 3.935 3.935 0 1 1 7.858 0 .5.5 0 0 1-.5.5Z"/>
        </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-default">
          <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
            <li>
              <a href="#" class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500" aria-current="page">Home</a>
            </li>
            <li>
              <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About</a>
            </li>
            <li>
              <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Services</a>
            </li>
            <li>
              <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Pricing</a>
            </li>
            <li>
              <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location) do |form| %>
  <% if location.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :designation, style: "display: block" %>
    <%= form.number_field :designation %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p>
    <strong>Latitude:</strong>
    <%= location.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= location.longitude %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= location.address %>
  </p>

  <p>
    <strong>Designation:</strong>
    <%= location.designation %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= location.name %>
  </p>

</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Show this location", @location %> |
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @location %>

<div>
  <%= link_to "Edit this location", edit_location_path(@location) %> |
  <%= link_to "Back to locations", locations_path %>

  <%= button_to "Destroy this location", @location, method: :delete %>
</div>

app/views/path_markers/_form.html.erb
<%= form_with(model: path_marker, class: "contents") do |form| %>
  <% if path_marker.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(path_marker.errors.count, "error") %> prohibited this path_marker from being saved:</h2>

      <ul>
        <% path_marker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/path_markers/_path_marker.html.erb
<div id="<%= dom_id(path_marker) %>">
 <%# need to include selection and deletion buttons that will remove the path_marker with a delete 
 event and a select action taht will hit the maps controller to select the new grouping %>
 <div class="container mt-2">
  <div class="flex flex-row text-center justify-between">
    <h3 class="text-lg font-semibold text-gray-900 dark:text-white"><%= path_marker.name %></h3>
    <div>
      <button type="button" class="py-2.5 px-5 me-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700"> Select </button> 
      <button type="button" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900"> Delete </button>
    </div>
  </div>
    <% path_marker.locations.each do |location| %>
      <div class="p-8 bg-white border-b border-gray-200 rounded-t-lg md:rounded-t-none md:rounded-ss-lg md:border-e dark:bg-gray-800 dark:border-gray-700">
          <blockquote class="max-w-2xl mx-auto mb-4 text-gray-500 lg:mb-8 dark:text-gray-400">
              <h3 class="text-lg font-semibold text-gray-900 dark:text-white"> <%= location.address %> </h3>
              <p class="my-4"> <%= location.latitude %> </p>
              <p class="my-4"> <%= location.longitude %> </p>
          </blockquote>
      </div>
    <% end %>
  </div>
</div>

app/views/path_markers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing path marker</h1>

  <%= render "form", path_marker: @path_marker %>

  <%= link_to "Show this path marker", @path_marker, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to path markers", path_markers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/path_markers/index.html.erb
<%= turbo_stream_from "path_markers" %>

app/views/path_markers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New path marker</h1>

  <%= render "form", path_marker: @path_marker %>

  <%= link_to "Back to path markers", path_markers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/path_markers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @path_marker %>

    <%= link_to "Edit this path_marker", edit_path_marker_path(@path_marker), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this path_marker", path_marker_path(@path_marker), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to path_markers", path_markers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<div class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">

<h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Editing user</h5>
<%= render "form", user: @user %>
<p class="font-normal text-gray-700 dark:text-gray-400"><%= link_to "Show this user", @user %> | <%= link_to "Back to users", users_path %></p>
</div>

app/views/users/index.html.erb
  <h1 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Users</h1>
  <div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              Name
            </th>
            <th scope="col" class="px-6 py-3">
              Email
            </th>
            <th scope="col" class="px-6 py-3">
              Actions
            </th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                <%= user.full_name %>
              </th>
              <td class="px-6 py-4">
                <%= user.email %>
              </td>
              <td class="flex px-6 py-4">
                <div class="font-medium text-blue-600 dark:text-blue-500 hover:underline"> <%= link_to "Edit", edit_user_path(user) %></div>
                <div class="ps-2 font-medium text-blue-600 dark:text-blue-500 hover:underline"> <%= link_to "Delete", user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %></div>
              </td>
            </tr>
          <% end %>
        </tbody>
    </table>
    <button type="button" class="py-2.5 px-5 m-2 ms-0 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700"> <%= link_to "New user", new_user_path %> </button>

app/views/users/new.html.erb
<div class="container">
  <h1 class="text-lg">New user</h1>
  <%= render "form", user: @user %>

  <div>
    <%= link_to "Back to users", users_path %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @user %>

  <div>
    <%= link_to "Edit this user", edit_user_path(@user) %> |
    <%= link_to "Back to users", users_path %>

    <%= button_to "Destroy this user", @user, method: :delete %>
  </div>
</div>